"""costo con 4 decimales, depto pvwin, busqueda de clave sin ceros

Revision ID: 0babdd4b65c1
Revises: d17f5cda3b48
Create Date: 2026-09-28 19:49:34.323292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0babdd4b65c1'
down_revision: Union[str, None] = 'd17f5cda3b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('pvwin_depto', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_categoria_pvwin_depto', 'categorias', ['negocio_id', 'pvwin_depto'])
    op.alter_column('lotes', 'costo_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('productos', 'costo',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.create_index('ix_productos_clave_sin_ceros', 'productos', [sa.text("ltrim(clave, '0')")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productos_clave_sin_ceros', table_name='productos')
    op.alter_column('productos', 'costo',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('lotes', 'costo_unitario',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_constraint('uq_categoria_pvwin_depto', 'categorias', type_='unique')
    op.drop_column('categorias', 'pvwin_depto')
    # ### end Alembic commands ###
