"""proveedores y entradas de mercancia

Revision ID: 0dd4042c31fe
Revises: d8b3e5f7a2c1
Create Date: 2026-09-29 15:10:57.821395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0dd4042c31fe'
down_revision: Union[str, None] = 'd8b3e5f7a2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rfc', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'nombre', name='uq_proveedor_nombre'),
    sa.UniqueConstraint('negocio_id', 'rfc', name='uq_proveedor_rfc')
    )
    op.create_index(op.f('ix_proveedores_negocio_id'), 'proveedores', ['negocio_id'], unique=False)
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('total_factura', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'proveedor_id', 'folio', name='uq_entrada_folio')
    )
    op.create_index(op.f('ix_entradas_negocio_id'), 'entradas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_entradas_proveedor_id'), 'entradas', ['proveedor_id'], unique=False)
    op.create_table('archivos_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('datos', sa.LargeBinary(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_factura_negocio_id'), 'archivos_factura', ['negocio_id'], unique=False)
    op.create_table('proveedor_equivalencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('clave_proveedor', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'descripcion', name='uq_equivalencia_descripcion')
    )
    op.create_index(op.f('ix_proveedor_equivalencias_clave_proveedor'), 'proveedor_equivalencias', ['clave_proveedor'], unique=False)
    op.create_index(op.f('ix_proveedor_equivalencias_negocio_id'), 'proveedor_equivalencias', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_proveedor_equivalencias_proveedor_id'), 'proveedor_equivalencias', ['proveedor_id'], unique=False)
    op.create_table('entrada_renglones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_proveedor', sa.String(), nullable=True),
    sa.Column('clave_proveedor', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('factor', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('piezas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('costo_pieza', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('numero_lote', sa.String(), nullable=True),
    sa.Column('caducidad', sa.Date(), nullable=True),
    sa.Column('costo_anterior', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('precio_anterior', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_nuevo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrada_renglones_entrada_id'), 'entrada_renglones', ['entrada_id'], unique=False)
    op.create_index(op.f('ix_entrada_renglones_producto_id'), 'entrada_renglones', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entrada_renglones_producto_id'), table_name='entrada_renglones')
    op.drop_index(op.f('ix_entrada_renglones_entrada_id'), table_name='entrada_renglones')
    op.drop_table('entrada_renglones')
    op.drop_index(op.f('ix_proveedor_equivalencias_proveedor_id'), table_name='proveedor_equivalencias')
    op.drop_index(op.f('ix_proveedor_equivalencias_negocio_id'), table_name='proveedor_equivalencias')
    op.drop_index(op.f('ix_proveedor_equivalencias_clave_proveedor'), table_name='proveedor_equivalencias')
    op.drop_table('proveedor_equivalencias')
    op.drop_index(op.f('ix_archivos_factura_negocio_id'), table_name='archivos_factura')
    op.drop_table('archivos_factura')
    op.drop_index(op.f('ix_entradas_proveedor_id'), table_name='entradas')
    op.drop_index(op.f('ix_entradas_negocio_id'), table_name='entradas')
    op.drop_table('entradas')
    op.drop_index(op.f('ix_proveedores_negocio_id'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
