"""cambio de producto

Revision ID: 27f89bf866b7
Revises: 6c8b71c00fa1
Create Date: 2026-09-28 21:48:33.312023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27f89bf866b7'
down_revision: Union[str, None] = '6c8b71c00fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic no detecta valores nuevos en tipos enum de PostgreSQL: se agregan a mano.
    op.execute("ALTER TYPE metodopago ADD VALUE IF NOT EXISTS 'SALDO_A_FAVOR'")
    op.execute("ALTER TYPE tipodevolucion ADD VALUE IF NOT EXISTS 'CAMBIO'")
    op.add_column('devoluciones', sa.Column('venta_nueva_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_devoluciones_venta_nueva', 'devoluciones', 'ventas', ['venta_nueva_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_devoluciones_venta_nueva', 'devoluciones', type_='foreignkey')
    op.drop_column('devoluciones', 'venta_nueva_id')
    # PostgreSQL no permite quitar valores de un enum; SALDO_A_FAVOR y CAMBIO
    # se quedan en los tipos (no estorban: nada los usa sin esta migración).
    # ### end Alembic commands ###
