"""cajas y turnos

Revision ID: 43c91ba16abf
Revises: 9f49bb059951
Create Date: 2026-09-28 20:43:08.515157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43c91ba16abf'
down_revision: Union[str, None] = '9f49bb059951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'nombre', name='uq_caja_por_negocio')
    )
    op.create_index(op.f('ix_cajas_negocio_id'), 'cajas', ['negocio_id'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MANANA', 'TARDE', name='tipoturno'), nullable=False),
    sa.Column('fondo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('abierto_por_id', sa.Integer(), nullable=False),
    sa.Column('abierto_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrado_por_id', sa.Integer(), nullable=True),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('efectivo_esperado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tarjeta_esperado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efectivo_contado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tarjeta_contado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia_tarjeta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas_cierre', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['abierto_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['cerrado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_caja_id'), 'turnos', ['caja_id'], unique=False)
    op.create_index(op.f('ix_turnos_negocio_id'), 'turnos', ['negocio_id'], unique=False)
    op.create_index('uq_turno_abierto_por_caja', 'turnos', ['caja_id'], unique=True, postgresql_where=sa.text('cerrado_en IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_turno_abierto_por_caja', table_name='turnos', postgresql_where=sa.text('cerrado_en IS NULL'))
    op.drop_index(op.f('ix_turnos_negocio_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_caja_id'), table_name='turnos')
    op.drop_table('turnos')
    sa.Enum(name='tipoturno').drop(op.get_bind())
    op.drop_index(op.f('ix_cajas_negocio_id'), table_name='cajas')
    op.drop_table('cajas')
    # ### end Alembic commands ###
