"""pedidos a proveedores

Revision ID: 4698642a1e3c
Revises: a3d5f7b9c1e2
Create Date: 2026-09-29 19:08:49.505242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4698642a1e3c'
down_revision: Union[str, None] = 'a3d5f7b9c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADO', 'RECIBIDO', 'CANCELADO', name='estadopedido'), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cerrado_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'folio', name='uq_pedido_folio_por_negocio')
    )
    op.create_index(op.f('ix_pedidos_negocio_id'), 'pedidos', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_pedidos_proveedor_id'), 'pedidos', ['proveedor_id'], unique=False)
    op.create_table('pedido_entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entrada_id')
    )
    op.create_index(op.f('ix_pedido_entradas_pedido_id'), 'pedido_entradas', ['pedido_id'], unique=False)
    op.create_table('pedido_renglones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_esperado', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_renglones_pedido_id'), 'pedido_renglones', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_renglones_producto_id'), 'pedido_renglones', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_renglones_producto_id'), table_name='pedido_renglones')
    op.drop_index(op.f('ix_pedido_renglones_pedido_id'), table_name='pedido_renglones')
    op.drop_table('pedido_renglones')
    op.drop_index(op.f('ix_pedido_entradas_pedido_id'), table_name='pedido_entradas')
    op.drop_table('pedido_entradas')
    op.drop_index(op.f('ix_pedidos_proveedor_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_negocio_id'), table_name='pedidos')
    op.drop_table('pedidos')
    sa.Enum(name='estadopedido').drop(op.get_bind())
    # ### end Alembic commands ###
