"""cancelaciones y devoluciones

Revision ID: 5f382e57e2e2
Revises: f345b1ee02df
Create Date: 2026-09-28 20:58:44.361857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f382e57e2e2'
down_revision: Union[str, None] = 'f345b1ee02df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devoluciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CANCELACION', 'DEVOLUCION', name='tipodevolucion'), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('efectivo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tarjeta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoluciones_negocio_id'), 'devoluciones', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_devoluciones_turno_id'), 'devoluciones', ['turno_id'], unique=False)
    op.create_index(op.f('ix_devoluciones_venta_id'), 'devoluciones', ['venta_id'], unique=False)
    op.create_table('devolucion_renglones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('venta_renglon_lote_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devoluciones.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['venta_renglon_lote_id'], ['venta_renglon_lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devolucion_renglones_devolucion_id'), 'devolucion_renglones', ['devolucion_id'], unique=False)
    op.create_index(op.f('ix_devolucion_renglones_venta_renglon_lote_id'), 'devolucion_renglones', ['venta_renglon_lote_id'], unique=False)
    op.add_column('venta_renglon_lotes', sa.Column('cantidad_devuelta', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta_renglon_lotes', 'cantidad_devuelta')
    op.drop_index(op.f('ix_devolucion_renglones_venta_renglon_lote_id'), table_name='devolucion_renglones')
    op.drop_index(op.f('ix_devolucion_renglones_devolucion_id'), table_name='devolucion_renglones')
    op.drop_table('devolucion_renglones')
    op.drop_index(op.f('ix_devoluciones_venta_id'), table_name='devoluciones')
    op.drop_index(op.f('ix_devoluciones_turno_id'), table_name='devoluciones')
    op.drop_index(op.f('ix_devoluciones_negocio_id'), table_name='devoluciones')
    op.drop_table('devoluciones')
    sa.Enum(name='tipodevolucion').drop(op.get_bind())
    # ### end Alembic commands ###
