"""configuracion de impresora y ticket

Revision ID: 6c8b71c00fa1
Revises: 5f382e57e2e2
Create Date: 2026-09-28 21:33:10.341393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c8b71c00fa1'
down_revision: Union[str, None] = '5f382e57e2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Con add_column, Alembic no crea el tipo enum en PostgreSQL: se crea a mano.
    modo = sa.Enum('NINGUNA', 'RED', 'AGENTE', name='modoimpresora')
    modo.create(op.get_bind(), checkfirst=True)
    op.add_column('cajas', sa.Column('impresora_modo', modo, server_default='NINGUNA', nullable=False))
    op.add_column('cajas', sa.Column('impresora_direccion', sa.String(), nullable=True))
    op.add_column('cajas', sa.Column('impresora_token', sa.String(), nullable=True))
    op.add_column('cajas', sa.Column('impresora_columnas', sa.Integer(), server_default='48', nullable=False))
    op.add_column('negocios', sa.Column('ticket_encabezado', sa.String(), nullable=True))
    op.add_column('negocios', sa.Column('ticket_pie', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negocios', 'ticket_pie')
    op.drop_column('negocios', 'ticket_encabezado')
    op.drop_column('cajas', 'impresora_columnas')
    op.drop_column('cajas', 'impresora_token')
    op.drop_column('cajas', 'impresora_direccion')
    op.drop_column('cajas', 'impresora_modo')
    sa.Enum(name='modoimpresora').drop(op.get_bind())
    # ### end Alembic commands ###
