"""logo en el ticket

Revision ID: 8afa6b8d9a2c
Revises: a67f23bf3c50
Create Date: 2026-09-29 21:10:03.919908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8afa6b8d9a2c'
down_revision: Union[str, None] = 'a67f23bf3c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocios', sa.Column('ticket_logo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negocios', 'ticket_logo')
    # ### end Alembic commands ###
