"""datos fiscales del negocio

Revision ID: a67f23bf3c50
Revises: b960ec12dded
Create Date: 2026-09-29 20:54:09.416510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a67f23bf3c50'
down_revision: Union[str, None] = 'b960ec12dded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocios', sa.Column('razon_social', sa.String(), nullable=True))
    op.add_column('negocios', sa.Column('rfc', sa.String(), nullable=True))
    op.add_column('negocios', sa.Column('regimen_fiscal', sa.String(), nullable=True))
    op.add_column('negocios', sa.Column('codigo_postal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negocios', 'codigo_postal')
    op.drop_column('negocios', 'regimen_fiscal')
    op.drop_column('negocios', 'rfc')
    op.drop_column('negocios', 'razon_social')
    # ### end Alembic commands ###
