"""facturas cfdi a clientes

Revision ID: b0ddf1565304
Revises: d54db4733594
Create Date: 2026-09-29 23:10:07.127094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0ddf1565304'
down_revision: Union[str, None] = 'd54db4733594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_fiscales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('rfc', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo_postal', sa.String(), nullable=False),
    sa.Column('regimen_fiscal', sa.String(), nullable=False),
    sa.Column('uso_cfdi', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'rfc', name='uq_cliente_rfc_por_negocio')
    )
    op.create_index(op.f('ix_clientes_fiscales_negocio_id'), 'clientes_fiscales', ['negocio_id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('VIGENTE', 'CANCELADA', name='estadofactura'), nullable=False),
    sa.Column('receptor_rfc', sa.String(), nullable=False),
    sa.Column('receptor_nombre', sa.String(), nullable=False),
    sa.Column('receptor_codigo_postal', sa.String(), nullable=False),
    sa.Column('receptor_regimen', sa.String(), nullable=False),
    sa.Column('uso_cfdi', sa.String(), nullable=False),
    sa.Column('forma_pago', sa.String(), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ieps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pac', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('fecha_timbrado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('pdf', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_fiscales.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'serie', 'folio', name='uq_factura_folio'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('venta_id')
    )
    op.create_index(op.f('ix_facturas_cliente_id'), 'facturas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_facturas_negocio_id'), 'facturas', ['negocio_id'], unique=False)
    op.add_column('negocios', sa.Column('factura_serie', sa.String(), server_default='C', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negocios', 'factura_serie')
    op.drop_index(op.f('ix_facturas_negocio_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cliente_id'), table_name='facturas')
    op.drop_table('facturas')
    sa.Enum(name='estadofactura').drop(op.get_bind())
    op.drop_index(op.f('ix_clientes_fiscales_negocio_id'), table_name='clientes_fiscales')
    op.drop_table('clientes_fiscales')
    # ### end Alembic commands ###
