"""margen por rango de costo en categorias

Revision ID: b960ec12dded
Revises: 4698642a1e3c
Create Date: 2026-09-29 19:51:37.415463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b960ec12dded'
down_revision: Union[str, None] = '4698642a1e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('limite_costo', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('categorias', sa.Column('margen_arriba_limite', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'margen_arriba_limite')
    op.drop_column('categorias', 'limite_costo')
    # ### end Alembic commands ###
