"""redondeo de precio de venta por negocio

Revision ID: d17f5cda3b48
Revises: ec08d65b28b2
Create Date: 2026-09-28 19:38:13.587851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd17f5cda3b48'
down_revision: Union[str, None] = 'ec08d65b28b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocios', sa.Column('redondeo_precio_venta', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negocios', 'redondeo_precio_venta')
    # ### end Alembic commands ###
