"""logo de la farmacia aparte de la imagen de inicio

Revision ID: d54db4733594
Revises: 8afa6b8d9a2c
Create Date: 2026-09-29 22:50:14.277461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd54db4733594'
down_revision: Union[str, None] = '8afa6b8d9a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocios', sa.Column('marca_url', sa.String(), nullable=True))
    op.add_column('negocios', sa.Column('marca_imagen', sa.LargeBinary(), nullable=True))
    op.add_column('negocios', sa.Column('marca_tipo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negocios', 'marca_tipo')
    op.drop_column('negocios', 'marca_imagen')
    op.drop_column('negocios', 'marca_url')
    # ### end Alembic commands ###
