"""producto granel impuestos revision, lote por categoria, ajustes inventario

Revision ID: ec08d65b28b2
Revises: c99da47a8b3c
Create Date: 2026-09-28 19:31:31.034210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec08d65b28b2'
down_revision: Union[str, None] = 'c99da47a8b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajustes_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('IMPORTACION', 'AJUSTE', 'MERMA', 'CAPTURA_CADUCIDAD', name='tipoajuste'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ajustes_inventario_lote_id'), 'ajustes_inventario', ['lote_id'], unique=False)
    op.create_index(op.f('ix_ajustes_inventario_negocio_id'), 'ajustes_inventario', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_ajustes_inventario_producto_id'), 'ajustes_inventario', ['producto_id'], unique=False)
    op.add_column('categorias', sa.Column('controla_lote', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # Renombrado a mano: autogenerate lo detectaba como borrar codigo_barras
    # y crear clave, lo que perdía los datos.
    op.alter_column('productos', 'codigo_barras', new_column_name='clave')
    op.add_column('productos', sa.Column('clave_sat', sa.String(), nullable=True))
    op.add_column('productos', sa.Column('laboratorio', sa.String(), nullable=True))
    op.add_column('productos', sa.Column('factor_conversion', sa.Numeric(precision=10, scale=3), server_default='1', nullable=False))
    op.add_column('productos', sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    op.add_column('productos', sa.Column('ieps_porcentaje', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    op.add_column('productos', sa.Column('minimo', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('productos', sa.Column('maximo', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('productos', sa.Column('requiere_revision', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('productos', sa.Column('motivo_revision', sa.String(), nullable=True))
    op.alter_column('productos', 'precio_venta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index('ix_productos_codigo_barras', table_name='productos')
    op.create_index(op.f('ix_productos_clave'), 'productos', ['clave'], unique=False)
    op.create_unique_constraint('uq_producto_clave_por_negocio', 'productos', ['negocio_id', 'clave'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_producto_clave_por_negocio', 'productos', type_='unique')
    op.drop_index(op.f('ix_productos_clave'), table_name='productos')
    op.alter_column('productos', 'precio_venta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('productos', 'motivo_revision')
    op.drop_column('productos', 'requiere_revision')
    op.drop_column('productos', 'maximo')
    op.drop_column('productos', 'minimo')
    op.drop_column('productos', 'ieps_porcentaje')
    op.drop_column('productos', 'iva_porcentaje')
    op.drop_column('productos', 'factor_conversion')
    op.drop_column('productos', 'laboratorio')
    op.drop_column('productos', 'clave_sat')
    op.alter_column('productos', 'clave', new_column_name='codigo_barras')
    op.create_index('ix_productos_codigo_barras', 'productos', ['codigo_barras'], unique=False)
    op.drop_column('categorias', 'controla_lote')
    op.drop_index(op.f('ix_ajustes_inventario_producto_id'), table_name='ajustes_inventario')
    op.drop_index(op.f('ix_ajustes_inventario_negocio_id'), table_name='ajustes_inventario')
    op.drop_index(op.f('ix_ajustes_inventario_lote_id'), table_name='ajustes_inventario')
    op.drop_table('ajustes_inventario')
    sa.Enum(name='tipoajuste').drop(op.get_bind())
    # ### end Alembic commands ###
