"""ventas en espera

Revision ID: ec5feedba685
Revises: b7e4a1c9d2f3
Create Date: 2026-09-29 13:19:32.030499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ec5feedba685'
down_revision: Union[str, None] = 'b7e4a1c9d2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas_en_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('renglones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('articulos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_en_espera_caja_id'), 'ventas_en_espera', ['caja_id'], unique=False)
    op.create_index(op.f('ix_ventas_en_espera_negocio_id'), 'ventas_en_espera', ['negocio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_en_espera_negocio_id'), table_name='ventas_en_espera')
    op.drop_index(op.f('ix_ventas_en_espera_caja_id'), table_name='ventas_en_espera')
    op.drop_table('ventas_en_espera')
    # ### end Alembic commands ###
