"""ventas renglones lotes y pagos

Revision ID: f345b1ee02df
Revises: 43c91ba16abf
Create Date: 2026-09-28 20:49:39.482009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f345b1ee02df'
down_revision: Union[str, None] = '43c91ba16abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('COMPLETADA', 'CANCELADA', name='estadoventa'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ieps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'folio', name='uq_venta_folio_por_negocio')
    )
    op.create_index(op.f('ix_ventas_created_at'), 'ventas', ['created_at'], unique=False)
    op.create_index(op.f('ix_ventas_negocio_id'), 'ventas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_ventas_turno_id'), 'ventas', ['turno_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='metodopago'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recibido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cambio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_venta_id'), 'pagos', ['venta_id'], unique=False)
    op.create_table('venta_renglones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ieps_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ieps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_renglones_producto_id'), 'venta_renglones', ['producto_id'], unique=False)
    op.create_index(op.f('ix_venta_renglones_venta_id'), 'venta_renglones', ['venta_id'], unique=False)
    op.create_table('venta_renglon_lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renglon_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['renglon_id'], ['venta_renglones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_renglon_lotes_lote_id'), 'venta_renglon_lotes', ['lote_id'], unique=False)
    op.create_index(op.f('ix_venta_renglon_lotes_renglon_id'), 'venta_renglon_lotes', ['renglon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_renglon_lotes_renglon_id'), table_name='venta_renglon_lotes')
    op.drop_index(op.f('ix_venta_renglon_lotes_lote_id'), table_name='venta_renglon_lotes')
    op.drop_table('venta_renglon_lotes')
    op.drop_index(op.f('ix_venta_renglones_venta_id'), table_name='venta_renglones')
    op.drop_index(op.f('ix_venta_renglones_producto_id'), table_name='venta_renglones')
    op.drop_table('venta_renglones')
    op.drop_index(op.f('ix_pagos_venta_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_ventas_turno_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_negocio_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_created_at'), table_name='ventas')
    op.drop_table('ventas')
    sa.Enum(name='metodopago').drop(op.get_bind())
    sa.Enum(name='estadoventa').drop(op.get_bind())
    # ### end Alembic commands ###
